@HotelListing.API_HostAddress = https://localhost:7245


###
GET {{HotelListing.API_HostAddress}}/api/hotels
###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  //Hotel
}

###

@id=0
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  //Hotel
}

###
