@HotelListing API_HostAddress = https://localhost:7245
@HotelListing.API_HostAddress = https://localhost:7245


###
GET {{HotelListing.API_HostAddress}}/api/hotels
###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  //Hotel
}

###

@id=0
DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  //Hotel
}

###

GET {{HotelListing API_HostAddress}}/api/countries

###

POST {{HotelListing API_HostAddress}}/api/countries
Content-Type: application/json

{
  //Country
}

###

DELETE {{HotelListing API_HostAddress}}/api/countries/{{id}}

###

GET {{HotelListing API_HostAddress}}/api/countries/{{id}}

###

PUT {{HotelListing API_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  //Country
}

###
